package dynamox

import "errors"

var (
	ErrCtxQueryNil                    = errors.New("CtxQuery cannot be nil")
	ErrInsufficientMember             = errors.New("insufficient member")
	ErrInsufficientCompositeKeySrc    = errors.New("insufficient compositeKey sources")
	ErrinsufficientParseCompositeKey  = errors.New("insufficient parse-compositeKey")
	ErrInsufficientRequiredMembers    = errors.New("insufficient required members in CtxQuery")
	ErrExpectedListAttribute          = errors.New("expected L attribute")
	ErrExpectedMapAttribute           = errors.New("expected M attribute")
	ErrExpectedStringAttribute        = errors.New("expected S attribute")
	ErrExpectedNumberAttribute        = errors.New("expected N attribute")
	ErrUnexpectedPartitionKey         = errors.New("unexpected partition key")
	ErrUnexpectedSortKey              = errors.New("unexpected sort key")
	ErrUnexpectedPartitionItem        = errors.New("unexpected patrition item")
	ErrUnexpectedIndexKind            = errors.New("unexpected index kind")
	ErrUnexpectedIndexFormat          = errors.New("unexpected index format")
	ErrRequiredIndexName              = errors.New("required indexName")
	ErrRequiredPartitionKey           = errors.New("required partitionKey")
	ErrRequiredSortKey                = errors.New("required sortKey")
	ErrRequiredKeyAndValue            = errors.New("required key and value")
	ErrReturnValuesSetToInvalidValue  = errors.New("returnValues set to invalid value")
	ErrReturnValuesNotSet             = errors.New("returnValues is not set in CtxQuery")
	ErrOutputNilPointer               = errors.New("output cannot be nil-pointer")
	ErrUnsupportedAttrValueTypeForKey = errors.New("unsupported AttributeValue type for key")
	ErrBeginsWithPrefixType           = errors.New("beginsWith prefix must be string")
	ErrBetweenUpperValue              = errors.New("between must have secondary value")
	ErrUnembedModel                   = errors.New("unembeded dynamodel.Model")
	ErrNotFoundItem                   = errors.New("not found item")
	ErrEmptyForUpdate                 = errors.New("empty for update")
	ErrInvalidAttributeDefinition     = errors.New("invalid attribute definition")
	ErrOutMustBePointerToSlice        = errors.New("out must be pointer to slice")
	ErrUnprocessedItems               = errors.New("check UnprocessedItems")
)
